DEBUG = True
DEMO_URL = 'http://127.0.0.1:5000'
CLIENT_DOWNLOAD_URL = 'http://www.litefac.com/assets/litefac.apk'

RECAPTCHA_USE_SSL = False
RECAPTCHA_PUBLIC_KEY = '6LfYmOkSAAAAAOosWJGTAyHrkpHprDagb37l0lxt'
RECAPTCHA_PRIVATE_KEY = '6LfYmOkSAAAAAOQfH9HORNa9LlOajHXGB-VTU2TO'
RECAPTCHA_OPTIONS = {'theme': 'clean'}

SECRET_KEY = 'ooghisei'
CSRF_SECRET_KEY = SECRET_KEY
